GET https://localhost:7188/api/Appointments/review
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYXVudGllQHBhcmxvci5jb20iLCJqdGkiOiI3MzM2MWNiNi04ZDk5LTQ3NzItODE0NC1lYjNkY2Q2ODBmZTUiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsImV4cCI6MTc3MzE5ODM1OCwiaXNzIjoiQXVudGllc1BhcmxvciIsImF1ZCI6IkF1bnRpZXNQYXJsb3JVc2VycyJ9.qKTRAQQjKzrUpXpyccVUMboIGUFDb267IuCND1Po0WU